---
- hosts: server2
  user: test
  sudo: yes
  tasks:
    - name: Install httpd package
      yum: name=httpd state=installed
      when: ansible_os_family == "RedHat"
    - name: Install apache2 package
      apt: name=apache2 state=installed
      when: ansible_os_family == "Debian"
    - name: copy index file
      copy: src=index.html dest=/var/www/html/index.html
    - name: start the httpd service
      service: name=httpd state=started
