---
- hosts: server2
  user: test
  sudo: yes
  tasks:
    - name: Install httpd package
      yum: name=httpd state=installed
      tags:
         - package
    - name: copy index file
      copy: src=index.html dest=/var/www/html/index.html
      tags:
         - copy
    - name: start the httpd service
      service: name=httpd state=started
      tags:
         - always
