---
- hosts: '{{host}}'
  user: test
  sudo: yes
  vars:
       pkg: httpd
  vars_files:
        - abc.yml
  vars_prompt:
        - name: pkg2
          prompt: Enter the package name
          private: no
  tasks:
    - name: Install httpd package
      yum: name={{pkg}} state=installed
    - name: Install curl package
      yum: name={{pkg1}} state=installed
    - name: Install telnet package
      yum: name={{pkg2}} state=installed
    - name: copy index file
      copy: src=index.html dest=/var/www/html/index.html
    - name: start the httpd service
      service: name={{pkg}} state=started
